version: 2.1


orbs:
  aws-ecr: circleci/aws-ecr@8.2.1
  aws-ecs: circleci/aws-ecs@3.2

jobs:
  lint-test:
    working_directory: ~/auth-api
    docker:
      - image: circleci/node:16
      - image: circleci/mongo:5.0
    environment:
      - NODE_ENV: test
      - MONGODB_URL: mongodb://localhost:27017/buy-chain
    steps:
      - checkout
      - run:
          name: Install node packages from package.json
          command: npm install
      - run:
          name: Lint
          command: npm run lint-no-fix
      - run:
          name: Unit test
          command: npm run test-unit
      - run:
          name: Seeding
          command: npm run test-integration-seeding
      - run:
          name: Run the auth-api in the background to see
          command: npm start
          background: true
      # - run:
      #     name: Integration test
      #     command: npm run test-integration
  
workflows:
  build_and_push_image:
    jobs:
      - lint-test
      - aws-ecr/build-and-push-image:
          requires:
            - lint-test
          context: dev
          dockerfile: Dockerfile
          path: .
          repo: buychain-dev-auth-api
          tag: "latest"
